% Arellano-Valle and Bolfarine generalized t distribution for dimension L
function y = logtpdfL(logDetGamma, mahalx, alpha, L)
    y = gammaln(alpha+L/2) ...
        - gammaln(alpha) ...
        - (L/2)*log(2*pi) ...
        - logDetGamma ...
        - (alpha+L/2)*(log(mahalx/2 + 1)); % 1x1 normalization constant
end
