% Arellano-Valle and Bolfarine generalized t distribution for dimension D
function y = logtpdfD(logDetSigma, mahaly, alpha, gammakn, D)
    y = gammaln(alpha+D/2) ...
        - gammaln(alpha) ...
        - (D/2)*log(2*pi) ...
        - (D/2)*log(gammakn) ...
        - logDetSigma ...
        - (alpha+D/2)*(log(mahaly./(2*gammakn) + 1)); % 1x1 normalization constant
end
