fname = '/home/omontigon/Documents/dataIRM/Bruker/Braveheart/Braveheart-06-6_cineASL_short-2023-02-17091509_marquage.json';
fid = fopen(fname);
raw = fread(fid,inf);
str = char(raw');
fclose(fid); 
val = jsondecode(str);

acqp = [val.ACQ_grad_matrix.value,...
        val.ACQ_fov.value,...
        val.ACQ_slice_sepn.value,...
        val.ACQ_NSLICES.value,...
        val.ACQ_slice_thick.value,...
        val.ACQ_slice_sepn_mode.value,...
        val.ACQ_NI.value,...
        val.ACQ_obj_order.value];

method = [val.PVM_SPackArrReadOffset.value,...
          val.PVM_SPackArrPhase1Offset.value,...
          val.PVM_SPackArrSliceOffset.value,...
          val.PVM_SPackArrGradOrient.value,...
          val.PVM_SliceGeo.value,...
          val.PVM_SPackArrSliceOrient.value];

reco = [val.RECO_offset.value,...
        val.RECO_ft_size.value,...
        val.RECO_size.value,...
        val.RECO_fov.value,...
        val.RECO_transposition.value];

visupars = [val.VisuCoreFrameCount.value,...
            val.VisuCoreOrientation.value];

orientation = val.SliceOrientation.value;

[filepath,name,ext] = fileparts(which('MRIManager.jar'));
javaclasspath(fullfile(filepath,[name,ext]));
brukerParavision.AffineQuaternionBruker_mp3.main(acqp, method, reco, visupars, orientation)

% [filepath,name,ext] = fileparts(which('Affine_MP3.jar'));
% javaclasspath(fullfile(filepath,[name,ext]));
% AffineQuaternionBruker_mp3.main({}, {}, {}, {}, {})
